"""Add operation media to ReportMedia and Timeline

Revision ID: 07a7a50c3973
Revises: bef1e383ba84
Create Date: 2026-07-03 22:56:16.377786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a7a50c3973'
down_revision: Union[str, Sequence[str], None] = 'bef1e383ba84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    rm_columns = [col['name'] for col in inspector.get_columns('report_media')]
    if 'assignment_id' not in rm_columns:
        op.add_column('report_media', sa.Column('assignment_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'report_media', 'incident_assignments', ['assignment_id'], ['id'], ondelete='CASCADE')
    if 'original_filename' not in rm_columns:
        op.add_column('report_media', sa.Column('original_filename', sa.String(), nullable=True))
    if 'file_size' not in rm_columns:
        op.add_column('report_media', sa.Column('file_size', sa.Integer(), nullable=True))
    if 'created_at' not in rm_columns:
        op.add_column('report_media', sa.Column('created_at', sa.DateTime(), nullable=True))
        
    rte_columns = [col['name'] for col in inspector.get_columns('rescue_timeline_events')]
    if 'media_id' not in rte_columns:
        op.add_column('rescue_timeline_events', sa.Column('media_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'rescue_timeline_events', 'report_media', ['media_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rescue_timeline_events', type_='foreignkey')
    op.drop_column('rescue_timeline_events', 'media_id')
    op.drop_constraint(None, 'report_media', type_='foreignkey')
    op.drop_column('report_media', 'created_at')
    op.drop_column('report_media', 'file_size')
    op.drop_column('report_media', 'original_filename')
    op.drop_column('report_media', 'assignment_id')
    # ### end Alembic commands ###
