"""add admin report attachments

Revision ID: 0ca07f0bf93d
Revises: 59a6ab763846
Create Date: 2026-07-05 14:35:27.316554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca07f0bf93d'
down_revision: Union[str, Sequence[str], None] = '59a6ab763846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_report_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_admin_report_attachments_id'), 'admin_report_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_admin_report_attachments_incident_id'), 'admin_report_attachments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_admin_report_attachments_uploaded_at'), 'admin_report_attachments', ['uploaded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_report_attachments_uploaded_at'), table_name='admin_report_attachments')
    op.drop_index(op.f('ix_admin_report_attachments_incident_id'), table_name='admin_report_attachments')
    op.drop_index(op.f('ix_admin_report_attachments_id'), table_name='admin_report_attachments')
    op.drop_table('admin_report_attachments')
    # ### end Alembic commands ###
