"""Add Post Incident Report models

Revision ID: 241a9a726f41
Revises: ceb0858b660e
Create Date: 2026-07-03 23:47:47.297862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241a9a726f41'
down_revision: Union[str, Sequence[str], None] = 'ceb0858b660e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_incident_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('casualties', sa.Integer(), nullable=True),
    sa.Column('people_rescued', sa.Integer(), nullable=True),
    sa.Column('injuries', sa.Integer(), nullable=True),
    sa.Column('fatalities', sa.Integer(), nullable=True),
    sa.Column('property_damage', sa.Text(), nullable=True),
    sa.Column('resources_used', sa.Text(), nullable=True),
    sa.Column('team_members', sa.Text(), nullable=True),
    sa.Column('weather_conditions', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['incident_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_incident_reports_assignment_id'), 'post_incident_reports', ['assignment_id'], unique=True)
    op.create_index(op.f('ix_post_incident_reports_id'), 'post_incident_reports', ['id'], unique=False)
    op.create_index(op.f('ix_post_incident_reports_incident_id'), 'post_incident_reports', ['incident_id'], unique=False)
    op.create_table('post_incident_report_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_incident_report_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_incident_report_id'], ['post_incident_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_post_incident_report_attachments_id'), 'post_incident_report_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_post_incident_report_attachments_post_incident_report_id'), 'post_incident_report_attachments', ['post_incident_report_id'], unique=False)
    op.create_index(op.f('ix_post_incident_report_attachments_uploaded_at'), 'post_incident_report_attachments', ['uploaded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_incident_report_attachments_uploaded_at'), table_name='post_incident_report_attachments')
    op.drop_index(op.f('ix_post_incident_report_attachments_post_incident_report_id'), table_name='post_incident_report_attachments')
    op.drop_index(op.f('ix_post_incident_report_attachments_id'), table_name='post_incident_report_attachments')
    op.drop_table('post_incident_report_attachments')
    op.drop_index(op.f('ix_post_incident_reports_incident_id'), table_name='post_incident_reports')
    op.drop_index(op.f('ix_post_incident_reports_id'), table_name='post_incident_reports')
    op.drop_index(op.f('ix_post_incident_reports_assignment_id'), table_name='post_incident_reports')
    op.drop_table('post_incident_reports')
    # ### end Alembic commands ###
