"""Add independent assignment lifecycles

Revision ID: 3620739710eb
Revises: 5390d1ecd032
Create Date: 2026-06-29 21:06:17.670226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3620739710eb'
down_revision: Union[str, Sequence[str], None] = '5390d1ecd032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_assignments', sa.Column('status', sa.String(), nullable=True))
    op.add_column('incident_assignments', sa.Column('accepted_at', sa.DateTime(), nullable=True))
    op.add_column('incident_assignments', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    op.add_column('incident_assignments', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('incident_assignments', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.add_column('incident_assignments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_assignments', 'updated_at')
    op.drop_column('incident_assignments', 'rejection_reason')
    op.drop_column('incident_assignments', 'completed_at')
    op.drop_column('incident_assignments', 'rejected_at')
    op.drop_column('incident_assignments', 'accepted_at')
    op.drop_column('incident_assignments', 'status')
    # ### end Alembic commands ###
