"""add device columns

Revision ID: 5390d1ecd032
Revises: f7dd219d9a70
Create Date: 2026-06-29 13:09:18.563163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5390d1ecd032'
down_revision: Union[str, Sequence[str], None] = 'f7dd219d9a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_media', sa.Column('report_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'report_media', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.add_column('report_reactions', sa.Column('report_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'report_reactions', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.add_column('reports', sa.Column('title', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('users', sa.Column('fcm_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('last_longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('last_local_unit', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_location_update', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_location_update')
    op.drop_column('users', 'last_local_unit')
    op.drop_column('users', 'last_longitude')
    op.drop_column('users', 'last_latitude')
    op.drop_column('users', 'fcm_token')
    op.drop_column('reports', 'severity')
    op.drop_column('reports', 'title')
    op.drop_constraint(None, 'report_reactions', type_='foreignkey')
    op.drop_column('report_reactions', 'report_id')
    op.drop_constraint(None, 'report_media', type_='foreignkey')
    op.drop_column('report_media', 'report_id')
    # ### end Alembic commands ###
