"""add report columns

Revision ID: 59a6ab763846
Revises: 3a619a963d6c
Create Date: 2026-07-04 21:02:12.954219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a6ab763846'
down_revision: Union[str, Sequence[str], None] = '3a619a963d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('location', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'sms_reports', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sms_reports', type_='foreignkey')
    op.drop_column('reports', 'longitude')
    op.drop_column('reports', 'latitude')
    op.drop_column('reports', 'location')
    # ### end Alembic commands ###
