"""Add Edit & Delete Support for Rescue Timeline Events

Revision ID: bef1e383ba84
Revises: 191715fbe83b
Create Date: 2026-07-03 22:23:42.309510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef1e383ba84'
down_revision: Union[str, Sequence[str], None] = '191715fbe83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rescue_timeline_events', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('rescue_timeline_events', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('rescue_timeline_events', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'rescue_timeline_events', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rescue_timeline_events', type_='foreignkey')
    op.drop_column('rescue_timeline_events', 'is_edited')
    op.drop_column('rescue_timeline_events', 'updated_by')
    op.drop_column('rescue_timeline_events', 'updated_at')
    # ### end Alembic commands ###
