"""Add title to report_media

Revision ID: ceb0858b660e
Revises: 07a7a50c3973
Create Date: 2026-07-03 23:11:43.281857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb0858b660e'
down_revision: Union[str, Sequence[str], None] = '07a7a50c3973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('report_media')]
    if 'title' not in columns:
        op.add_column('report_media', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_media', 'title')
    # ### end Alembic commands ###
