"""Refactor status lifecycle

Revision ID: faae09e01a9a
Revises: 3620739710eb
Create Date: 2026-07-01 12:12:10.867380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faae09e01a9a'
down_revision: Union[str, Sequence[str], None] = '3620739710eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not inspector.has_table('status_history'):
        op.create_table('status_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('entity_type', sa.String(), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=False),
        sa.Column('old_status', sa.String(), nullable=True),
        sa.Column('new_status', sa.String(), nullable=False),
        sa.Column('changed_by', sa.UUID(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('remarks', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_status_history_entity_id'), 'status_history', ['entity_id'], unique=False)
        op.create_index(op.f('ix_status_history_entity_type'), 'status_history', ['entity_type'], unique=False)
        op.create_index(op.f('ix_status_history_id'), 'status_history', ['id'], unique=False)
    columns = [col['name'] for col in inspector.get_columns('rescue_updates')]
    if 'message' not in columns:
        op.add_column('rescue_updates', sa.Column('message', sa.Text(), nullable=True))
    if 'image_url' not in columns:
        op.add_column('rescue_updates', sa.Column('image_url', sa.String(), nullable=True))
    if 'location_lat' not in columns:
        op.add_column('rescue_updates', sa.Column('location_lat', sa.String(), nullable=True))
    if 'location_lng' not in columns:
        op.add_column('rescue_updates', sa.Column('location_lng', sa.String(), nullable=True))
    
    # --- Data Migration Start ---
    # Map Incident Statuses
    op.execute("UPDATE incidents SET status = 'In Progress' WHERE status = 'Verified Rescue In Progress'")
    op.execute("UPDATE incidents SET status = 'Controlled' WHERE status = 'Verified Controlled'")
    op.execute("UPDATE incidents SET status = 'Closed' WHERE status = 'Verified and Closed'")
    
    # Map RescueUpdate statuses to IncidentAssignments before dropping the column
    if 'status' in columns:
        op.execute("""
            UPDATE incident_assignments 
            SET status = 'Accepted'
            FROM rescue_updates 
            WHERE rescue_updates.incident_id = incident_assignments.incident_id 
            AND rescue_updates.rescue_team_id = incident_assignments.team_id 
            AND rescue_updates.status = 'acknowledged' 
            AND incident_assignments.status = 'Assigned'
        """)
        op.execute("""
            UPDATE incident_assignments 
            SET status = 'In Progress'
            FROM rescue_updates 
            WHERE rescue_updates.incident_id = incident_assignments.incident_id 
            AND rescue_updates.rescue_team_id = incident_assignments.team_id 
            AND rescue_updates.status = 'in_progress'
        """)
        op.execute("""
            UPDATE incident_assignments 
            SET status = 'Completed'
            FROM rescue_updates 
            WHERE rescue_updates.incident_id = incident_assignments.incident_id 
            AND rescue_updates.rescue_team_id = incident_assignments.team_id 
            AND rescue_updates.status = 'resolved'
        """)
    # --- Data Migration End ---

    if 'acknowledged_at' in columns:
        op.drop_column('rescue_updates', 'acknowledged_at')
    if 'in_progress_at' in columns:
        op.drop_column('rescue_updates', 'in_progress_at')
    if 'status' in columns:
        op.drop_column('rescue_updates', 'status')
    if 'post_incident_submitted_at' in columns:
        op.drop_column('rescue_updates', 'post_incident_submitted_at')
    if 'is_acknowledged' in columns:
        op.drop_column('rescue_updates', 'is_acknowledged')
    if 'resolved_at' in columns:
        op.drop_column('rescue_updates', 'resolved_at')
    if 'updated_at' in columns:
        op.drop_column('rescue_updates', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rescue_updates', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('rescue_updates', sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('rescue_updates', sa.Column('is_acknowledged', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('rescue_updates', sa.Column('post_incident_submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('rescue_updates', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('rescue_updates', sa.Column('in_progress_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('rescue_updates', sa.Column('acknowledged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('rescue_updates', 'location_lng')
    op.drop_column('rescue_updates', 'location_lat')
    op.drop_column('rescue_updates', 'image_url')
    op.drop_column('rescue_updates', 'message')
    op.drop_index(op.f('ix_status_history_id'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_entity_type'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_entity_id'), table_name='status_history')
    op.drop_table('status_history')
    # ### end Alembic commands ###
