"""add_final_admin_report

Revision ID: fd26d60be548
Revises: faae09e01a9a
Create Date: 2026-07-02 13:28:03.504957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd26d60be548'
down_revision: Union[str, Sequence[str], None] = 'faae09e01a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('final_admin_report', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'final_admin_report')
    # ### end Alembic commands ###
